### ISSUE TITLE
unable to parse with example AceParser code

### ISSUE THREAD

**Issue by slpls** [delph-in/pydelphin#118]
Hi there, 

I am working from the ace tutorial and and I don't seem to be able to get an initial example working. I've tried most of the initial parsing examples, and I receive the same error. Below is a snippet of code that produces the error, with the complete error pasted below it. 

Thank you for your work on this library!

**Code snippet**
from pydelphin.delphin.interfaces.ace import AceParser

with AceParser(''/Users/stephanie/projects/ace-0.9.25/erg-1212-osx-0.9.25.dat') as parser:
    response = parser.interact('Cats sleep.')
    print(response.result(0)['mrs'])
    print(response.result(0).mrs())

**Error**
ERROR:root:Failed to get ACE version number.
Traceback (most recent call last):
  File "/Users/stephanie/projects/SemanticRepresentationParser.py", line 4, in <module>
    with AceParser('/Users/stephanie/projects/ace-0.9.25/erg-1212-osx-0.9.25.dat') as parser:
  File "/Users/stephanie/projects/pydelphin/delphin/interfaces/ace.py", line 151, in __init__
    self.ace_version = _ace_version(self.executable)
  File "/Users/stephanie/projects/pydelphin/delphin/interfaces/ace.py", line 457, in _ace_version
    out = check_output([executable, '-V'], universal_newlines=True)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ace'

**Comment by goodmami** [comment]
Hi, thanks for the thanks, and for the bug report.

I believe the "Failed to get ACE version number." error is a bit misleading. The real problem is the last line: "No such file or directory: 'ace'". This suggests that PyDelphin is unable to find your ACE executable. 

First, ensure that ACE is installed, or at least downloaded: http://sweaglesw.org/linguistics/ace/

Second, PyDelphin assumes that `ace` is executable as a system command (on Linux that means that `ace` is in a directory listed in the environment variable `PATH`; I'm not a Mac user so I'm not certain what that translates to, but this [StackOverflow answer](https://stackoverflow.com/a/16288733/1441112) might be informative).

Also, if you look further down in the tutorial, there is the [Additional Arguments](https://github.com/delph-in/pydelphin/wiki/Ace-Tutorial#additional-arguments) section. The `executable` parameter to the ace commands allow you to specify the path of the `ace` binary without modifying PATH. Try following the example in that section and replace the value of `executable` with the path to your ACE binary.

Does that help? Maybe I should update the tutorial to make that more clear...

**Comment by slpls** [comment]
That does help! I will adjust my $PATH first thing at work tomorrow and let you know how it goes. Please let me know if it would be helpful for me to report back how I end up setting this up on a Mac.

**Comment by goodmami** [comment]
Yes, please reply to record if that solution fixed the problem. If there were any other steps you did to get things working on Mac, add those too and I can put them in the tutorial or other documentation. If there are other unresolved problems, please open a separate issue so they get recorded. Finally, close the issue if the solution resolves things for you.

Thanks!

**Comment by goodmami** [comment]
@slpls, did this work for you?

**Comment by goodmami** [comment]
I have not received a response in over a month, and I did not see evidence of any bug, so I will close the issue.
