### ISSUE TITLE
'Conjunction' object has no attribute '__setitem__'

### ISSUE THREAD

**Issue by lmorgadodacosta** [delph-in/pydelphin#224]
I'm trying to set the STEM value of lexicon to a different value, but it seems that there is not ```
\_\_setitem\_\_ available.  

Here is an example lexical entry:
-----------------------------------
```
少于_v_1 := v_np_le &
  [ STEM < "少于" >,
    SYNSEM [ LOCAL.CAT.HEAD.CHAR [ FCHAR "少", LENGTH two ],
             LKEYS.KEYREL.PRED "hello" ],
    TRAITS native_token_list ].
```

This is the code snippet we tried:
-----------------------------------
```

from delphin import tdl
lex = {}
for event, obj, lineno in tdl.iterparse('lex-base.tdl'):
    if event == 'TypeDefinition':
        lex[obj.identifier] = obj
for l in lex:
    obj = lex[l]
    x = tdl.ConsList(values=[tdl.String('hello'),
                             tdl.String('goodbye')],
                     end=tdl.EMPTY_LIST_TYPE)
    obj['STEM'] = x
    print(tdl.format(obj))
```

**Comment by goodmami** [comment]
Thank you for the bug report (or perhaps feature request).

The tdl module constructs a number of objects for each TDL definition, so when you do `obj['STEM']` it gets the value of the 'STEM' feature of the AVM which is a term of the Conjunction inside the TypeDefinition that is `obj`. When you do `obj['STEM'] = ...` you are doing a `__setitem__()` call on the TypeDefinition which passes it along to the Conjunction, but the Conjunction does not have the method defined, as you've seen. So I think this is a really a bug than request for a missing feature.

For now you can make sure the `__setitem__` works on the AVM instead of the Conjunction by doing the following (which I worked out since we tried to figure this out yesterday):

```python
>>> obj.conjunction.terms[1]['STEM'] = tdl.ConsList(
...     [tdl.String('hi'), tdl.String('bye')],
...     end=tdl.EMPTY_LIST_TYPE)
>>> print(tdl.format(obj))
少于_v_1 := v_np_le &
  [ STEM < "hi", "bye" >,
    SYNSEM [ LOCAL.CAT.HEAD.CHAR [ FCHAR "少", LENGTH two ],
             LKEYS.KEYREL.PRED "hello" ],
    TRAITS native_token_list ].
```

This assumes that the AVM is the second item in the Conjunction's terms (where the first is the supertype), which should be true for lexicons. Otherwise you could add a line like this:

```python
>>> avm = next(
...     (term for term in obj.conjunction.terms if isinstance(term, tdl.AVM)),
...     None)
>>> avm['STEM'] = ...
```

I'll make sure this is a tested use case for v1.0.0. Thanks!

**Comment by lmorgadodacosta** [comment]
This works, thanks!
