### ISSUE TITLE
Support tab-separated-value items for mkprof

### ISSUE THREAD

**Issue by lmorgadodacosta** [delph-in/pydelphin#227]
Another related improvement to mkprof would be to allow the comment field to be populated. This is defined as i-comment :string in the relations file. When building profiles from corpora, we often want to include at least the docID+sentID.

**Comment by goodmami** [comment]
I agree it would be nice to get some use out of that field.

Do docID and sentID come from the corpora? Maybe in #226 you'd like to have `i-id` actually set to docID+sentID?

Either way, the question is how to get that info from the corpus into the test suite being built. There are variations on the wiki to the sentence-input format I use which include some more data, but it says they are obsolete: http://moin.delph-in.net/ItsdbReference#Text_Input_Formats

Anyway, suppose we've figured that out and put the data in some data structure `d`. The next question is how to tell `mkprof` how to put it where we want. We could introduce another option, something like `--set-field=item.i-comment=docID` which does `testsuite['item'][cur_item_idx]['i-comment'] = d['docID']`, but that's a bit ugly. Also, if you want to concatenate two fields (docID and sentID) together, we'd need to evaluate some kind of expression there (or you could combine them into a single field before importing, maybe).

**Comment by lmorgadodacosta** [comment]
I think you might be overthinking it.... The `i-id` is not really related with this issue, since the IDs are supposed to be unique across all profiles and, for some grammars like the ERG, different corpora (or research groups) have pre-assigned ID slots (e.g. Francis and I just decided to use some of hid allotted IDs for the new Learner Corpus -- and they are between  35,000,000 - 40,000,000); 

The way I see this would be that the sentence file would accept a second tab per line that would be triggered/read by  a subcommand (e.g. `--read-comments`):

For example:
`echo -e "A dog barks. \t Some comment here\n *Dog barks a. \t Another comment here" | delphin mkprof --relations ~/logon/lingo/lkb/src/tsdb/skeletons/english/Relations --start 15500 --read-comments newprof`

A simple interpretation of this would be that, with the subcommand `--read-comments`, `mkprof` requires a 2-column tab file as input where the second tab gets translated as the comment field.

In my opinion, the fact that some of these comments are used by certain groups to store different kinds/amounts of information should not impose on a structure that can be more flexible.

**Comment by arademaker** [comment]
Why not handle sent-ids in a similar fashion?

**Comment by goodmami** [comment]
@lmorgadodacosta Sorry my rhetoric was meant to illustrate the issues and to link similar ideas, not to put forth a serious proposal. Basically I'm not keen to introduce another microformat for a very specific use case. If we allow an option to read comments in a 2-column tab-separated file (without a header line), then what if someone wants to include another field, like `i-author`, or as @arademaker says, specific `i-id` values?

I can imagine adding something flexible to multiple use cases, such as some `--tsv` option (mutually exclusive with `--source` or `--in-place`) that expects the text input to be tab-separated-values but, crucially, *with* a header line:

```
i-input	i-comment	i-author
The dog barks.	comment	goodmami
...	...	...
```

If `i-id` is a column, it is used (and checked for uniqueness), otherwise it is generated.

But at some point your needs may outgrow what the command-line interface can provide, in which case the Python API would be better:

```python3
>>> ts = itsdb.TestSuite(path, 'path/to/relations')
>>> ts['item'].extend(...)
>>> ts.write()
```

**Comment by goodmami** [comment]
@lmorgadodacosta do you have any thoughts on the generic `--tsv` proposal, or just using the Python API?

**Comment by lmorgadodacosta** [comment]
I think what you proposed above is reasonable. From what I saw online, `i-author` is often used to register who created the profile. This means that having an option to provide the author for the entire skeleton would be nice (but not strictly necessary).

**Comment by goodmami** [comment]
Ok, I will slate this for 1.0.0, probably exactly as described unless I want to change the name of the `--tsv` option.

**Comment by goodmami** [comment]
I realized that having a tab-delimited file format was not really different from the TSDB `@`-delimited files except that it wouldn't allow for escaped tabs, etc. So you could also just write the item file with the fields you want and a custom `relations` file, then refresh (#232) the test suite with the proper `relations` file. However that is too much hassle.

Instead I changed `--tsv` described above to `--delimiter` (following the `cut` command). If `--delimiter="@"` it is split using the TSDB rules (including escaping). Otherwise it is split on the character using Python's `split()` string method. Otherwise it is the same as I've described above.

Do note that you'll need to put in a literal tab and not an escaped tab:

```console
$ delphin mkprof --input sentences profile --delimiter="	"  # ok
$ delphin mkprof --input sentences profile --delimiter="\t"  # nope
```

 In the terminal you can enter a literal tab with "Ctrl-v TAB". If this is too confusing I can probably convert the escape sequence in the code and otherwise require `--delimiter` to be one character and not a longer string.
