### ISSUE TITLE
python version support question

### ISSUE THREAD

**Issue by olzama** [delph-in/pydelphin#317]
Is it the case that pydelphin no longer supports 3.5? I seem to be having issues symptomatic of that, trying to run the latest version of the Matrix on my old ubuntu where I have everything set up. 

(This is just a question, so I am not sure an issue is the best way of doing that.)

**Comment by olzama** [comment]
Actually, this doesn't make sense, does it? 3.6 should be backward-compatible wrt 3.5, right? So, must be some other issue that I am having...

**Comment by olzama** [comment]
Sorry about the confusing comments. My question really is: should the latest version of the Matrix (which uses rtest.py which depends on pydelphin, and I think actually some other parts are using pydelphin as well now?) still work on 16.04 ubuntu? Or not?

**Comment by goodmami** [comment]
> Is it the case that pydelphin no longer supports 3.5?

PyDelphin has required at least 3.6 since version 1.2.0 (released in January this year). If you need to run on Python 3.5 you'll need to install the previous version of PyDelphin (1.1.0). You can see a note of the change in the [changelog](https://github.com/delph-in/pydelphin/blob/develop/CHANGELOG.md#v120) and the list of supported versions in the badge on the rendered README:

![pydelphin-python-version](https://user-images.githubusercontent.com/1428419/92980408-aeb5ad80-f4c8-11ea-8ee0-76c350c90716.png)

> 3.6 should be backward-compatible wrt 3.5, right?

3.6 is backward compatible with 3.5 but 3.5 is not forward compatible with 3.6.

> should the latest version of the Matrix (which uses rtest.py which depends on pydelphin, and I think actually some other parts are using pydelphin as well now?) still work on 16.04 ubuntu?

`rtest.py` requires at least PyDelphin 1.4.0 because of the parameter it uses to suppress printing PyDelphin's progress bar when processing.

The other parts of the Matrix use PyDelphin's tsdb module, and it might be *work* with PyDelphin v1.1.0, but since that version I've improved the way it prints dates in profiles and how it splits on newlines. That means it might give spurious failures or errors on profiles created in Windows that have `\r` partial newline sequences in the `i-input` field, and the profiles might not load in the [incr tsdb()] podium because of the way it prints dates.

I suggest upgrading to Python 3.6. Besides, Python 3.5 itself will reach end-of-life [at the end of this month](https://www.python.org/dev/peps/pep-0478/).

**Comment by olzama** [comment]
Right. That means ugrading the ubuntu; are you using 18 now? I tried 20 and I am not happy with it, I cannot set up folder sharing with the host, to name one thing.

**Comment by goodmami** [comment]
> That means upgrading the ubuntu

Or installing through other means, such as compiling from source (it's not too bad), or maybe the [deadsnakes](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) ppa is still working.

> are you using 18 now? I tried 20 and I am not happy with it, I cannot set up folder sharing with the host, to name one thing.

I'm using [Pop!_OS](https://pop.system76.com/) 20.04, which is an Ubuntu derivative. It's pretty great. I don't use a VM so I don't know about folder sharing.

**Comment by olzama** [comment]
The deadsnake is dead... :)
