### ISSUE TITLE
ace reports an unexpected total number of sentences in a profile

### ISSUE THREAD

**Issue by arademaker** [delph-in/pydelphin#339]
This is weird, all my profiles have 1000 items, but in two of them, ACE reported different numbers of total sentences. 807 and 1001 sentences, how is it possible? This is the last line printed by the `delphin mkprof ...`

```
NOTE: parsed 700 / 807 sentences, avg 659414k, time 4309.64990s
NOTE: parsed 867 / 1001 sentences, avg 649245k, time 4679.26416s
```

**Comment by goodmami** [comment]
This sounds like an ACE issue rather than a PyDelphin one. PyDelphin is not capturing or handling ACE's stderr. I'll close the issue, but feel free to reopen if you have evidence that PyDelphin is causing ACE to report this. I would also be very surprised if you're getting ACE stderr messages from `delphin mkprof`, as this command does not call ACE. Did you mean `delphin process`?

My guess as to why ACE reports the different number is that some of the items have `i-wf` of 2 or `i-length` of -1 or `i-difficulty` of -1, which may cause ACE to ignore them. Sometimes there are other issues, though, like malformed profiles.

**Comment by arademaker** [comment]
sure, yes, `delphin process ...`
