### ISSUE TITLE
MRS encoding in prolog 

### ISSUE THREAD

**Issue by arademaker** [delph-in/pydelphin#358]
https://github.com/delph-in/pydelphin/blob/b5c7094691f01a161983224fe78b2ad26e7fea9b/delphin/codecs/mrsprolog.py#L56

Where is the prolog format documented? What PSOA stands for? 

The variables properties seems to be ignored no manner how we call encode. Am I right?

**Comment by goodmami** [comment]
> Where is the prolog format documented?

I don't know if it is. I reverse engineered the format by looking at LKB outputs.

> What PSOA stands for?

Parameterized State Of Affairs (see http://lists.delph-in.net/archives/developers/2020/003156.html)

> The variables properties seems to be ignored no manner how we call encode. Am I right?

Correct. This is because the MRS-Prolog codec follows PyDelphin's [Codec API](https://pydelphin.readthedocs.io/en/latest/api/delphin.codecs.html#codec-api). See the section on [Variations](https://pydelphin.readthedocs.io/en/latest/api/delphin.codecs.html#variations). I don't think the Prolog form ever had variable properties encoded, so the codec doesn't support them.
