### ISSUE TITLE
Problem with wrong intrinsic variable for quantifier

### ISSUE THREAD

**Issue by AlexKuhnle** [delph-in/pydelphin#54]
I encountered a problem with the sentence: **"The big and brown dog barks."**
After parsing it with ACE, loading it via simplemrs, and outputting it via dmrx (and, optionally, going backwards again), the quantifier has the event var of "and" as intrinsic variable, hence RSTR-links to the "and" node. The problem seems to lie in the heuristic of choosing heads for EPs with equal handle in Xmrs.labelset_heads. I can't so far say what exactly goes wrong here, but since I am looking into this myself, I can probably suggest a solution in a few days. I would expect something like that the decision of the head gets influenced by the MRS-given intrinsic variable, if an EP in the equally-labeled candidate set shares it (would obviously only apply to quantifiers).
The sentence can't be re-generated because of this, however, if one doesn't transform to dmrx and back, everything works fine.

**Comment by goodmami** [comment]
Thanks for the report. Can you submit the MRS you are starting with? When I parse that sentence with the ERG 1214, I get two parses, and neither of them are the expected parse. The parses I do get have `_bark_n_1` instead of `_bark_v_1`.

But the head-finding heuristics do fail from time to time. I can't recreate what you describe with that sentence, but I can with a slightly different sentence: _The big and noisy dog barks._ (color names have their own peculiarities, which may prevent me from getting the parse you get). Anyway, here's the MRS I see:

```
[ LTOP: h0 INDEX: e2 [ e SF: prop TENSE: pres MOOD: indicative PROG: - PERF: - ]
  RELS: < [ _the_q_rel<0:3> LBL: h4 ARG0: x3 [ x PERS: 3 NUM: sg IND: + ] RSTR: h5 BODY: h6 ]
          [ "_big_a_1_rel"<4:7> LBL: h7 ARG0: e8 [ e SF: prop TENSE: untensed MOOD: indicative ] ARG1: x3 ]
          [ _and_c_rel<8:11> LBL: h9 ARG0: e10 [ e SF: prop TENSE: untensed MOOD: indicative ] L-INDEX: e8 R-INDEX: e11 [ e SF: prop ] L-HNDL: h7 R-HNDL: h12 ]
          [ "_noisy_a_1_rel"<12:17> LBL: h12 ARG0: e11 ARG1: x3 ]
          [ "_dog_n_1_rel"<18:21> LBL: h9 ARG0: x3 ]
          [ "_bark_v_1_rel"<22:28> LBL: h1 ARG0: e2 ARG1: x3 ] >
  HCONS: < h0 qeq h1 h5 qeq h9 > ]
```

And the DMRX:

```xml
<dmrs-list>
<dmrs cfrom="-1" cto="-1">
<node cfrom="0" cto="3" nodeid="10000"><realpred lemma="the" pos="q" /><sortinfo /></node>
<node cfrom="4" cto="7" nodeid="10001"><realpred lemma="big" pos="a" sense="1" /><sortinfo cvarsort="e" mood="indicative" sf="prop" tense="untensed" /></node>
<node cfrom="8" cto="11" nodeid="10002"><realpred lemma="and" pos="c" /><sortinfo cvarsort="e" mood="indicative" sf="prop" tense="untensed" /></node>
<node cfrom="12" cto="17" nodeid="10003"><realpred lemma="noisy" pos="a" sense="1" /><sortinfo cvarsort="e" sf="prop" /></node>
<node cfrom="18" cto="21" nodeid="10004"><realpred lemma="dog" pos="n" sense="1" /><sortinfo cvarsort="x" ind="+" num="sg" pers="3" /></node>
<node cfrom="22" cto="28" nodeid="10005"><realpred lemma="bark" pos="v" sense="1" /><sortinfo cvarsort="e" mood="indicative" perf="-" prog="-" sf="prop" tense="pres" /></node>
<link from="0" to="10005"><rargname /><post>H</post></link>
<link from="10000" to="10002"><rargname>RSTR</rargname><post>H</post></link>
<link from="10001" to="10004"><rargname>ARG1</rargname><post>NEQ</post></link>
<link from="10002" to="10001"><rargname>L-HNDL</rargname><post>HEQ</post></link>
<link from="10002" to="10001"><rargname>L-INDEX</rargname><post>NEQ</post></link>
<link from="10002" to="10003"><rargname>R-HNDL</rargname><post>HEQ</post></link>
<link from="10002" to="10003"><rargname>R-INDEX</rargname><post>NEQ</post></link>
<link from="10002" to="10004"><rargname /><post>EQ</post></link>
<link from="10003" to="10004"><rargname>ARG1</rargname><post>NEQ</post></link>
<link from="10005" to="10004"><rargname>ARG1</rargname><post>NEQ</post></link>
</dmrs>
</dmrs-list>
```

I believe the head-finding algorithm fails because the modifiers _big_ and _noisy_ point to their modifiees with `ARG1/NEQ` links, and the `_and_c` is then attached via an undirected `/EQ` link. (Aside: this doesn't seem like the ideal DMRS, but I don't have a better solution that would still scope.) Both `_and_c` and `_dog_n_1` look like head of that label-equality-set because neither point to each other (i.e., neither point to other elements within their label-equality-set). I can add additional heuristics, such as not having quantifiers link to things with an `e` cvarsort, or consider that `_and_c` links to `_dog_n_1` transitively. I tried to read the LKB source to see how it does this, but I'm not good at reading lisp. Let me know if you have any suggestions.

**Comment by goodmami** [comment]
Following up, I retract the suggestion to make a heuristic depend on the cvarsort, because those sorts are grammar specific (e.g. it may be `x` post SEM-I, but `ref-ind` grammar-internal, or possibly something else). Secondly, while there is indeed an issue with head finding, in this case the incorrect link comes from a quantifier, so it should be obvious what the target is (the quantified noun).

Regarding the head-finding heuristics, another good one might be the distance from the top.

**Comment by goodmami** [comment]
The recent commit (dbbf25d3f13260cf1d5572898e66e7a185b15d91) fixes the issue with quantifier links, but the head-finding thing is unresolved. I created #57 for that.

**Comment by AlexKuhnle** [comment]
The MRS I get is:
`[ LTOP: h0 INDEX: e2 [ e SF: prop TENSE: pres MOOD: indicative PROG: - PERF: - ] RELS: < [ _the_q_rel<0:3> LBL: h4 ARG0: x3 [ x PERS: 3 NUM: sg IND: + ] RSTR: h5 BODY: h6 ]  [ "_big_a_1_rel"<4:7> LBL: h7 ARG0: e8 [ e SF: prop TENSE: untensed MOOD: indicative PROG: bool PERF: - ] ARG1: x3 ]  [ _and_c_rel<8:11> LBL: h9 ARG0: e10 [ e SF: prop TENSE: untensed MOOD: indicative PROG: bool PERF: - ] L-INDEX: e8 R-INDEX: e11 [ e SF: prop ] L-HNDL: h7 R-HNDL: h12 ]  [ "_brown_a_1_rel"<12:17> LBL: h12 ARG0: e11 ARG1: x3 ]  [ "_dog_n_1_rel"<18:21> LBL: h9 ARG0: x3 ]  [ "_bark_v_1_rel"<22:28> LBL: h1 ARG0: e2 ARG1: x3 ] > HCONS: < h0 qeq h1 h5 qeq h9 > ICONS: < > ]`

I was asking Ann how she handles these cases: In short (if I understand correctly), there is a heuristic to find head**s** of equally-labeled EPs, based on having no outgoing variable links to other EPs in the set. Then for each of the head EPs a link is added. I think that your fix definitely makes sense, since quantifier EPs have a special role in MRS as being the only ones "without" really an intrinsic variable. Apart from that, I think that your head-heuristic also makes sense - only, instead of letting node id decide as a last instance, I wonder: Would there be problems in having multiple heads in this case (for the sake of DMRS-back-to-MRS conversion)?

**Comment by goodmami** [comment]
Thanks! I tried the sentence with the latest SVN version of the ERG and got the parse you have; strangely the regular demo site (http://erg.delph-in.net/) doesn't get any parses.

And I initially followed the Copestake 2009 ("Slacker Semantics") paper for finding heads. I also understand that there can be more than one head (the pyDelphin `Xmrs.labelset_heads()` function returns a list), but I think that not all heads are created equal (it's a sorted list, sorted using the heuristics described in #57), and the most "heady" one is selected as the target of the link. If there are multiple heads, the others get `/EQ` links with the headiest head. I use nodeid to approximate the surface order just as a last-case criterion for sorting heads. The LKB does the essentially the same thing (see `make-dmrs-eq-links` in lkb/src/rmrs/dmrs.lisp) with a comment that it should use CFROM eventually.

The code for EDS has more fine-grained head-finding criteria then either the LKB or pyDelphin (see `ed-select-representative` in lkb/src/mrs/dependencies.lisp). If I can't get pyDelphin to consistently give the appropriate link targets, I might try to more closely imitate either the DMRS or EDS methods from the LKB.
