### ISSUE TITLE
Problem with icons and omitted underspecified variable

### ISSUE THREAD

**Issue by AlexKuhnle** [delph-in/pydelphin#60]
There is a problem with omitted underspecified variables i and icons that refer to them. The sentence **_"Impressed by the cat, Kim laughed."_** should produce the following EP:
`[ _impress_v_1_rel<0:9> LBL: h7 ARG0: e8 [ e SF: prop TENSE: untensed MOOD: indicative ] ARG1: x9 ARG2: i10 ]`
Instead, it omits ARG2, but the icons list subsequently refers to it:
`ICONS: < e8 topic i10 >`

The same with the 1214 version, where icons are handled differently:
`[ _impress_v_1_rel<0:9> LBL: h7 ARG0: e8 [ e SF: prop TENSE: untensed MOOD: indicative ] ARG1: x9 ARG2: i10 ]
[ parg_d_rel LBL: h7 ARG0: e22 [ e SF: prop ] ARG1: e8 ARG2: i10 ]`

Overall, this should probably be parsed differently anyway, with i10 refering to the variable representing the subject of the main clause instead.

**Comment by goodmami** [comment]
Hi, I'm confused what the problem is here. Is there something wrong with DMRS->MRS conversion? pyDelphin currently does not handle ICONS in DMRS because, as far as I know, DMRS itself doesn't yet handle them. Or is pyDelphin doing something wrong with the variables when it parses SimpleMRS?

Here's the first MRS from the SVN version of the ERG as parsed by ACE:

```
[ LTOP: h0
  INDEX: e2 [ e SF: prop TENSE: past MOOD: indicative PROG: - PERF: - ]
  RELS: < [ subord_rel<0:21> LBL: h1 ARG0: e4 [ e SF: prop TENSE: untensed MOOD: indicative PROG: - PERF: - ] ARG1: h5 ARG2: h6 ]
   [ "_impress_v_1_rel"<0:9> LBL: h7 ARG0: e8 [ e SF: prop TENSE: untensed MOOD: indicative ] ARG1: x9 [ x PERS: 3 NUM: sg IND: + ] ARG2: i10 ]
   [ _the_q_rel<13:16> LBL: h11 ARG0: x9 RSTR: h12 BODY: h13 ]
   [ "_cat_n_1_rel"<17:21> LBL: h14 ARG0: x9 ]
   [ proper_q_rel<22:25> LBL: h15 ARG0: x3 [ x PERS: 3 NUM: sg IND: + ] RSTR: h16 BODY: h17 ]
   [ named_rel<22:25> LBL: h18 CARG: "Kim" ARG0: x3 ]
   [ "_laugh_v_at_rel"<26:34> LBL: h20 ARG0: e2 ARG1: x3 ] >
  HCONS: < h0 qeq h1 h5 qeq h20 h6 qeq h7 h12 qeq h14 h16 qeq h18 >
  ICONS: < e8 topic i10 > ]
```

Btw, while the SVN version of the ERG has ICONS, I don't think the 1214 version does. I'm don't know if the `ARG2` of `_impress_v_1` should in fact be the `ARG0` of Kim (e.g., `x3` above). That is, while it intuitively makes sense, I don't know if its actually dictated by the sentence structure. Also, it's possible that an interpretation of the sentence equates `i10` and `x3` (i.e., it's not necessarily the case that they refer to different things). There might be some information on the wiki (http://moin.delph-in.net/ErgSemantics/NonAdverbialClausalModifiers).

**Comment by AlexKuhnle** [comment]
Oh right, that was a mistake on my part - obviously the ICON information cannot "survive" a transformation to DMRS and back, but SimpleMRS is doing everything fine, as I confirmed now. Sorry for that!

**Comment by goodmami** [comment]
Ok, thanks for the follow-up. I'll try to add ICONS support to DMRS as soon as it's defined.
